Implement Event Manager v0.1.0
Bismarck-GM/microverse-associations pull request #2
Opened 2020-08-03 21:58 UTC by WinterCore

## Changes:
- Initialize rails project.
- Create models/migrations & add relations (events, users, event_user)
- Add forms for viewing, creating, and attending events.
- Add show events page.
- Add scopes used to filter past & future events.
- Add model for user invites (user_invite)
- Add form to allow event authors to invite users to their events.
- Implement Windows 98 styles (thanks to [98.css](https://jdan.github.io/98.css)
- Fix rubocop Shenanigans.
- Configure RSpec and capybara
- Add feature tests for the entire application using capybara.
- Add readme.
- Add demo gif.
- Add GitHub action to deploy the project to Heroku

2020-08-04 02:39 UTC, euqueme requested changes
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @WinterCore and @Bismarck-GM  :balloon: :lollipop: 

### Thank you for your submission :handshake: :handshake: your project works well and I especially like the style you've chosen for it it's original and stands out from the rest :alien: you've also made good use of indexes and your repo and readme are outstanding :1st_place_medal: :1st_place_medal: let's work on the following changes :construction: :construction_worker: :construction_worker_man: 

#### Behaviour

- [x] The user's show page displays events the user has created and events that the user is attending to separated in past and upcoming ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

- it seems that You are only displaying the events the user is attending or attended to you should also have a section of past and upcoming created events.

- I can't create past events so I couldn't test if your app has past events the live demo doesn't have past events either so let's remove this validation so it's possible to create past events in your app.

- You have a form to invite users to a specific event but the user doesn't have a way to confirm the invitation in fact it seems like this form is not doing anything really so I would suggest to add the confirmation form or to remove this feature from your project so it doesn't create confusion. 

#### Associations

##### User as event creator

- [x] I've put messages directly in your code where changes have to be made to be able to meet this requirement

#### Views & Helpers

* [x] View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb) There should be absolutely NO logic or complexity in views or partials.

  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Take a look at the following Resource to remove complexity from views** [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

- I've left comments directly in your views where I found if, if/else, unless and/or ternary operators, you should use helper methods to handle this complexity.

### That's it, team! :raised_hands: 

### Please :pray: do the changes :technologist: :technologist:  and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any question? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-08-04 02:39 UTC, euqueme commented on app/models/user.rb
> +  has_many :events
#### Associations

##### User as event creator

* [ ] User model: `has_many :events, foreign_key: :creator_id` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

- Even though the Events table uses the user_id attribute as the foreign key automatically you were asked to use the creator_id alias instead so let's make the changes to make it possible.

2020-08-04 02:39 UTC, euqueme commented on app/models/event.rb
> +  belongs_to :creator, class_name: User.name, foreign_key: 'user_id'
#### Associations

##### User as event creator

* [ ] Event model `belongs_to :creator, class_name: "User"` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

- No need to specify the foreign_key and the class_name calling the User.name to be able to use this association you have to create a migration that adds the creator_id attribute to the Events table

2020-08-04 02:39 UTC, euqueme commented on app/views/events/_invite_form.html.erb
> +<% end %>
- [ ] put the if statement in a partial that renders a partial containing the markup within the if statement so you don't have this complexity directly in the partial

2020-08-04 02:39 UTC, euqueme commented on app/views/layouts/application.html.erb
> +          <% end %>
- [ ] put the if statement in a helper method that renders the link instead of having this complexity directly in the view

2020-08-04 02:39 UTC, euqueme commented on app/views/partials/_flash_messages.html.erb
> +<% end %>
- [ ] put the if statement in a partial that renders a partial containing the markup within the if statement so you don't have this complexity directly in the partial

2020-08-04 02:39 UTC, euqueme commented on app/views/partials/_flash_messages.html.erb
> +<% end %>
- [ ] put the if statement in a partial that renders a partial containing the markup within the if statement so you don't have this complexity directly in the partial

2020-08-04 02:39 UTC, euqueme commented on app/views/partials/_form_errors.html.erb
> +<% end %>
- [ ] put the if statement in a partial that renders a partial containing the markup within the if statement so you don't have this complexity directly in the partial

2020-08-04 21:44 UTC, WinterCore commented
Hey @euqueme. Thanks for the amazing code review.

All the requested changes have been implemented.

Just a quick note regarding this
> You have a form to invite users to a specific event but the user doesn't have a way to confirm the invitation in fact it seems like this form is not doing anything really so I would suggest to add the confirmation form or to remove this feature from your project so it doesn't create confusion.

We add a new link `invites` to the home page. Clicking on that link will take you to a page that contains all the events you've been invited to. So hopefully this should help with the confusion.

2020-08-05 00:31 UTC, rOluochKe requested changes
Hello @WinterCore and @Bismarck-GM 
### You have put in some good work so far :clap: and for also making changes from the previous review. However, your project is not passing the linting.
- [x] Please, fix the errors raised by the linter and submit for another review.
- Happy coding!

By Raymond
Slack @iamraymond

2020-08-05 00:44 UTC, Bismarck-GM commented
Hi @rOluochKe the fail that you were seeing wasn't a Linter. It was Heroku deployment with GitHub Actions, and it failed because we reached the daily max of builds. There's no issues with the project.

Tried to contact you via Slack 5 mins after you submitted the comment but I couldn't reach you.

2020-08-05 00:44 UTC, Bismarck-GM commented
Deleted Heroku deployment file (hdeploy.yml) so it doesn't get confused for a linter.

2020-08-05 02:04 UTC, maelfosso approved these changes
# Congratulations :clap: 

Thank you for applying the suggested changes. :+1: 
You can merge it now :smirk_cat: 
Good continuation :handshake: 

Thanks 
Mael FOSSO

2020-08-05 02:10 UTC, merged